import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import React from 'react';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const Grold = localFont({
  src: '../font/Grold-Regular.ttf',
  display: 'swap'
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={Grold.className}>
				<div className='mx-auto max-w-[1366px] overflow-hidden'>
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
