import type { Metadata } from 'next';
import {} from 'next/font/google';
import './globals.css';
import React from 'react';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='font-mona'>
				<div className='mx-auto max-w-[1366px]'>
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
