import type { Metadata } from 'next';
import Hero from '@/components/pageSections/Hero';
import ServicesOne from '@/components/pageSections/ServicesOne';
import ServicesTwo from '@/components/pageSections/ServicesTwo';
import Faq from '@/components/pageSections/Faq';

export const metadata: Metadata = {
	title: 'Landify',
	description: 'Generated by create next app',
};

export default function Home() {
	return (
		<main className='overflow-hidden'>

			<Hero />

			<ServicesOne />

			<ServicesTwo />

			<Faq />
			
		</main>
	);
}
